platform :ios, '12'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HoExpandableTableView_Example' do
  pod 'HoExpandableTableView'

  target 'HoExpandableTableView_Tests' do
    inherit! :search_paths

    
  end
end
